name: ThurData Support Build

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-thurdata'
      - '[0-9]+.[0-9]+.[0-9]+-thurdata'

env:
  CUSTOM_VERSION: "-thurdata"

jobs:
  build-thurdata:
    uses: ./.github/workflows/flutter-build.yml
    with:
      upload-artifact: true
      upload-tag: ${{ github.ref_name }}
    secrets: inherit

