name: ThurData Support-UI Build

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-thurdatasupport'
      - '[0-9]+.[0-9]+.[0-9]+-thurdatasupport'

jobs:
  build-thurdata-ui:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout thurdata-ui branch
        uses: actions/checkout@v3
        with:
          ref: thurdata-ui

      - name: Run Flutter Build Workflow
        uses: ./.github/workflows/flutter-build.yml        
        with:
          upload-artifact: true
          upload-tag: "support"
        
